// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package container

import (
	"redis-like-golang/internal/adapter/handler"
	"redis-like-golang/internal/adapter/protocol"
	"redis-like-golang/internal/infrastructure/persistence"
	"redis-like-golang/internal/infrastructure/storage"
	"redis-like-golang/internal/usecase"
)

// Injectors from wire.go:

// InitializeContainer creates a new container with all dependencies using Wire
func InitializeContainer(opt persistence.AOFProviderOption) (*Container, func(), error) {
	keyValueRepository := storage.NewStore()
	persistenceRepository, err := persistence.NewAOFProvider(opt)
	if err != nil {
		return nil, nil, err
	}
	parser := protocol.NewParser()
	stats := usecase.NewStats(keyValueRepository)
	commandHandler := usecase.NewCommandHandler(keyValueRepository, persistenceRepository, stats, parser)
	tcpHandler := handler.NewTCPHandler(commandHandler, parser)
	container := NewContainer(keyValueRepository, persistenceRepository, parser, commandHandler, tcpHandler)
	return container, func() {
	}, nil
}
